apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
spec:
  destination:
    namespace: demo-gitops-mprj
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bgd
    repoURL: https://github.com/EricSaDev/openshift-gitops-demo
    targetRevision: deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: false